### ISSUE TITLE
[Feature] 로그인/메인/마이페이지 UI 구현

### ISSUE THREAD

**Issue by urapp13ofmyeye** [2024-LIKELION-ECurator/ECurator_FE#3]
## ✔️ Issue

로그인/메인/마이페이지 UI 구현

## 📝 To-do

- [x] 로그인, 회원가입 페이지 UI 구현
- [x] 마이페이지 UI 구현
- [x] 메인페이지 UI 구현
- [ ] API 연동
